---
- name: Remove and clean in remote host
  hosts: all
  vars:
    ansible_user: vagrant
  remote_user: "{{ ansible_user }}"
  become: true
  tasks:
    - name: Run make fclean
      become: true
      command: make fclean
      args:
        chdir: /home/{{ ansible_user }}/inception
    - name: Remove the inception directory
      become: true
      file:
        path: /home/{{ ansible_user }}/inception
        state: absent
