---
- name: Remote Project Structure
  hosts: all
  remote_user: "{{ ansible_user }}"
  become: true
  tasks:
    - name: Create Project on remote server
      file:
        path: /home/{{ ansible_user }}/inception
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Copy The Project To Remote Server
      copy:
        src: ../srcs/
        dest: /home/{{ ansible_user }}/inception

    - name: Add WordPress Volume Data
      file:
        path: /home/{{ ansible_user }}/inception/data/wp
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add Mariadb Volume Data
      file:
        path: /home/{{ ansible_user }}/inception/data/db
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Edit WP_URL ENV value
      lineinfile:
        path: /home/{{ ansible_user }}/inception/.env
        regexp: '^WP_URL='
        line: "WP_URL={{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"

    - name: Edit WORDPRESS_HOST_NAME ENV value
      lineinfile:
        path: /home/{{ ansible_user }}/inception/.env
        regexp: '^WORDPRESS_HOST_NAME='
        line: "WORDPRESS_HOST_NAME={{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
