---
- name: Run The Project
  hosts: all
  remote_user: "{{ ansible_user }}"
  become: true
  tasks:
    - name: Run make
      become: true
      command: make
      args:
        chdir: /home/{{ ansible_user }}/inception
